### ISSUE TITLE
java.lang.NullPointerException 	at java.base/java.util.Objects.requireNonNull(Objects.java:209) 	at com.intellij.platform.lsp.impl.LspServerImpl.getLsp4jServer(LspServerImpl.java:96) 	at com.semgrep.idea.lsp.SemgrepLspServer$Companion.getInstances(SemgrepLspServer.kt:26)

### ISSUE THREAD

**Issue by Maskhe** [semgrep/semgrep-intellij#80]
![image](https://github.com/user-attachments/assets/dc653e42-baa8-410a-890b-5bf61691881f)

**Comment by ajbt200128** [comment]
What version of the plugin is this with? What version of semgrep?
